### ISSUE TITLE
Illegal first Move

### ISSUE THREAD

**Issue by pan1997** [akshaykgupta/Tak-sim#7]
The first move is always a move to place a flat stone of your opponent, and cannot be moveing the stone of your own color that was just placed by the opponent.

pankaj@pankaj-HP-Pavilion-15-Notebook-PC:~/programming/COL333/Tak-sim$ python client.py localhost 12345 RandomPlayer.py 
You are player 2
You are alloted a time of 360s

The other player played Fa5
Time remaining is: 360s
Possible moves: ['Fa1', 'Fb1', 'Fc1', 'Fd1', 'Fe1', 'Fa2', 'Fb2', 'Fc2', 'Fd2', 'Fe2', 'Fa3', 'Fb3', 'Fc3', 'Fd3', 'Fe3', 'Fa4', 'Fb4', 'Fc4', 'Fd4', 'Fe4', 'Fb5', 'Fc5', 'Fd5', 'Fe5', '1a5-1', '1a5>1']
Chosen move: 1a5-1
You played 1a5-1
The other player played Fd5
Time remaining is: 360s
Possible moves: ['Fa1', 'Sa1', 'Ca1', 'Fb1', 'Sb1', 'Cb1', 'Fc1', 'Sc1', 'Cc1', 'Fd1', 'Sd1', 'Cd1', 'Fe1', 'Se1', 'Ce1', 'Fa2', 'Sa2', 'Ca2', 'Fb2', 'Sb2', 'Cb2', 'Fc2', 'Sc2', 'Cc2', 'Fd2', 'Sd2', 'Cd2', 'Fe2', 'Se2', 'Ce2', 'Fa3', 'Sa3', 'Ca3', 'Fb3', 'Sb3', 'Cb3', 'Fc3', 'Sc3', 'Cc3', 'Fd3', 'Sd3', 'Cd3', 'Fe3', 'Se3', 'Ce3', 'Fb4', 'Sb4', 'Cb4', 'Fc4', 'Sc4', 'Cc4', 'Fd4', 'Sd4', 'Cd4', 'Fe4', 'Se4', 'Ce4', 'Fa5', 'Sa5', 'Ca5', 'Fb5', 'Sb5', 'Cb5', 'Fc5', 'Sc5', 'Cc5', 'Fe5', 'Se5', 'Ce5', '1a4+1', '1a4-1', '1a4>1']
Chosen move: Sb3
You played Sb3
The other player played Fd4
Time remaining is: 360s
Possible moves: ['Fa1', 'Sa1', 'Ca1', 'Fb1', 'Sb1', 'Cb1', 'Fc1', 'Sc1', 'Cc1', 'Fd1', 'Sd1', 'Cd1', 'Fe1', 'Se1', 'Ce1', 'Fa2', 'Sa2', 'Ca2', 'Fb2', 'Sb2', 'Cb2', 'Fc2', 'Sc2', 'Cc2', 'Fd2', 'Sd2', 'Cd2', 'Fe2', 'Se2', 'Ce2', 'Fa3', 'Sa3', 'Ca3', 'Fc3', 'Sc3', 'Cc3', 'Fd3', 'Sd3', 'Cd3', 'Fe3', 'Se3', 'Ce3', 'Fb4', 'Sb4', 'Cb4', 'Fc4', 'Sc4', 'Cc4', 'Fe4', 'Se4', 'Ce4', 'Fa5', 'Sa5', 'Ca5', 'Fb5', 'Sb5', 'Cb5', 'Fc5', 'Sc5', 'Cc5', 'Fe5', 'Se5', 'Ce5', '1b3+1', '1b3-1', '1b3<1', '1b3>1', '1a4+1', '1a4-1', '1a4>1']
Chosen move: 1a4>1
You played 1a4>1
The other player played Fe3
Time remaining is: 360s
Possible moves: ['Fa1', 'Sa1', 'Ca1', 'Fb1', 'Sb1', 'Cb1', 'Fc1', 'Sc1', 'Cc1', 'Fd1', 'Sd1', 'Cd1', 'Fe1', 'Se1', 'Ce1', 'Fa2', 'Sa2', 'Ca2', 'Fb2', 'Sb2', 'Cb2', 'Fc2', 'Sc2', 'Cc2', 'Fd2', 'Sd2', 'Cd2', 'Fe2', 'Se2', 'Ce2', 'Fa3', 'Sa3', 'Ca3', 'Fc3', 'Sc3', 'Cc3', 'Fd3', 'Sd3', 'Cd3', 'Fa4', 'Sa4', 'Ca4', 'Fc4', 'Sc4', 'Cc4', 'Fe4', 'Se4', 'Ce4', 'Fa5', 'Sa5', 'Ca5', 'Fb5', 'Sb5', 'Cb5', 'Fc5', 'Sc5', 'Cc5', 'Fe5', 'Se5', 'Ce5', '1b3+1', '1b3-1', '1b3<1', '1b3>1', '1b4+1', '1b4<1', '1b4>1']
Chosen move: Sc5
You played Sc5
The other player played Fe2
Time remaining is: 360s
Possible moves: ['Fa1', 'Sa1', 'Ca1', 'Fb1', 'Sb1', 'Cb1', 'Fc1', 'Sc1', 'Cc1', 'Fd1', 'Sd1', 'Cd1', 'Fe1', 'Se1', 'Ce1', 'Fa2', 'Sa2', 'Ca2', 'Fb2', 'Sb2', 'Cb2', 'Fc2', 'Sc2', 'Cc2', 'Fd2', 'Sd2', 'Cd2', 'Fa3', 'Sa3', 'Ca3', 'Fc3', 'Sc3', 'Cc3', 'Fd3', 'Sd3', 'Cd3', 'Fa4', 'Sa4', 'Ca4', 'Fc4', 'Sc4', 'Cc4', 'Fe4', 'Se4', 'Ce4', 'Fa5', 'Sa5', 'Ca5', 'Fb5', 'Sb5', 'Cb5', 'Fe5', 'Se5', 'Ce5', '1b3+1', '1b3-1', '1b3<1', '1b3>1', '1b4+1', '1b4<1', '1b4>1', '1c5-1', '1c5<1', '1c5>1']
Chosen move: Sa5
You played Sa5
The other player played Fe1
Time remaining is: 360s
Possible moves: ['Fa1', 'Sa1', 'Ca1', 'Fb1', 'Sb1', 'Cb1', 'Fc1', 'Sc1', 'Cc1', 'Fd1', 'Sd1', 'Cd1', 'Fa2', 'Sa2', 'Ca2', 'Fb2', 'Sb2', 'Cb2', 'Fc2', 'Sc2', 'Cc2', 'Fd2', 'Sd2', 'Cd2', 'Fa3', 'Sa3', 'Ca3', 'Fc3', 'Sc3', 'Cc3', 'Fd3', 'Sd3', 'Cd3', 'Fa4', 'Sa4', 'Ca4', 'Fc4', 'Sc4', 'Cc4', 'Fe4', 'Se4', 'Ce4', 'Fb5', 'Sb5', 'Cb5', 'Fe5', 'Se5', 'Ce5', '1b3+1', '1b3-1', '1b3<1', '1b3>1', '1b4+1', '1b4<1', '1b4>1', '1a5-1', '1a5>1', '1c5-1', '1c5<1', '1c5>1']
Chosen move: Cc2
You played Cc2
The other player played Ce4
YOU LOSE :(

**Comment by akshaykgupta** [comment]
Thanks. Fixed.
