### ISSUE TITLE
No Draw Game.

### ISSUE THREAD

**Issue by pan1997** [akshaykgupta/Tak-sim#8]
The rules say that a game is draw when it ends with equal number of flatstones of each player on the board.(Black will have one left to play but the game will be terminated) The current implementation states it to be a win for black. What will be the final take on this matter.

**Comment by akshaykgupta** [comment]
Hmm I'm not sure why you say black will have one left to play. Equal number of flatstones means equal number of flatstones on _top_. So either player could be out of pieces. And in case of equality, we consider the person who ran out of pieces to be the loser. (As a side note, the scoring here will reflect that it was a close game).

**Comment by pan1997** [comment]
I meant to say that the game ends with equal number of flats on top but white was out of peices, and black had one left.

**Comment by akshaykgupta** [comment]
Ok, in that particular case, black will win.
